document.write("<div id=sudsclickstreamdiv style='position: absolute;width:80;top:-300;left:100;visibility: visible;z-index: 1'></div>");
var _S_JV_="webbug_meta_ref_mod_iframe:7.02";var cp_rf="http://beacon.sina.com.cn/a.gif";var cp_rf_d="http://beacon.sina.com.cn/d.gif";var cp_url="http://beacon.sina.com.cn/bcn_ck.html";var _S_CID_=0;var _S_DPID_="-9999-0-0-1";var _S_FL=0;
var _S_DOMAINKEY=".sina.";var _S_DOMAINROOT="sina.com.cn";var _S_PW_=window;var _S_PWD_=_S_PW_.document;var _S_BN_=navigator;var _S_NAN_=_S_BN_.appName;var _S_NAV_=_S_BN_.appVersion;var _S_DROT_="";
var _DOMAIN_LIST_=new Array("blog","news","sport","www","finance","game","ent","jczs","junshi","astro","auto","baby","book","comic","stock","tech","vogue","ladys","eladies","supergirl","yuan","jiaoyou","man","cul","edu","exam","cctv","chat","kid","life","live","living","weather","home","housing","neverforget","rss","see","sinapay","teen","yue","2004","bj.house","forum","bbs","people","mail","vip","search","school","bn","unipro","gov","iask","jx.edu","city","sol","sinapay","sy.house","cp.house");
var _CHANNELID_LIST_=new Array(346,1,6,30,31,115,28,27,27,54,33,20,112,55,31,2,8,8,8,8,296,296,133,60,42,352,386,70,205,52,52,8,281,30,62,348,294,337,315,138,28,249,62,59,59,59,71,71,73,138,167,179,257,292,301,308,315,315,317,317);
function _S_gCidbDm(){pUrl=_S_PWD_.URL;pUrl=pUrl.toLowerCase();pChid=0;var mReg;for(var i in _DOMAIN_LIST_){ps=pUrl.indexOf(_DOMAIN_LIST_[i]);if(ps>0){if(pUrl.indexOf(".sina.com.",ps)>0) return _CHANNELID_LIST_[i];} } return pChid;}
function _S_gMeta(MName){pMeta=_S_PWD_.getElementsByName(MName);if(pMeta.length>0){return pMeta[0].content;} else{return "";}}
function _S_gCid(){_S_CID_=346;}
_S_gCid();
function _S_gUCk(ckName){var _S_PWDC_=_S_PWD_.cookie;var start=_S_PWDC_.indexOf(ckName+"=");if (-1==start){return "";} start=_S_PWDC_.indexOf("=", start)+1;var end=_S_PWDC_.indexOf(";", start);if (0 >=end){end=_S_PWDC_.length;} ckValue=_S_PWDC_.substring(start, end);return ckValue;}
function _S_sUCk(ckName, ckValue, ckdays){if (ckValue !=null){if (("undefined"==ckdays)||(null==ckdays)){_S_PWD_.cookie=ckName + "=" + ckValue + "; domain="+_S_DOMAINROOT+"; path=/" ;} else{var now=new Date();var time=now.getTime();time=time + 86400000 * ckdays;now.setTime(time);time=now.getTime();_S_PWD_.cookie=ckName + "=" + ckValue + "; domain="+_S_DOMAINROOT+"; expires=" +now.toUTCString()+ "; path=/";} }}
function _S_gfBcn(f_url){var _sl_scsd=_S_PWD_.getElementById("sudsclickstreamdiv");if(null!=_sl_scsd){_sl_scsd.innerHTML="<iframe frameborder='0' height='0' width='0' marginheight='0' marginwidth='0' src='"+f_url+"'></iframe>";}} 
function _S_p2Bcn(strQuest,wb_url){var _sl_scsd=_S_PWD_.getElementById("sudsclickstreamdiv");if(null!=_sl_scsd){_sl_scsd.innerHTML="<img src='"+wb_url+"?"+strQuest+"' border='0' alt='' />";}} 
function _S_gUrl2Pth(_sp_url){var pagePath=_sp_url;var pstart=pagePath.indexOf("sina.com.cn");if (pstart> 0){var tmpStr=pagePath.substring(0,pstart);tmpStr=tmpStr+"sr"+pagePath.substring(pstart+11);pagePath=tmpStr;} return pagePath;}
function _S_gConType(){var contype="";try{_S_PWD_.body.addBehavior("#default#clientCaps");contype=_S_PWD_.body.connectionType;}catch(E){contype="unkown";} return contype;} 
function _S_isHome(){var cul="";var isH="";try{cul=_S_PWD_.location.href;_S_PWD_.body.addBehavior("#default#homePage");isH=_S_PWD_.body.isHomePage(cul)?"Y":"N";}catch(E){isH="unkown";} return isH;}
function _S_gJVer(){var p,appsign,appver,jsver=1.0,isN6=0;if ('Microsoft Internet Explorer'==_S_NAN_){appsign='MSIE';p=_S_NAV_.indexOf(appsign);if (p>=0){appver=parseInt(_S_NAV_.substring(p+5));if (3<=appver){jsver=1.1; if (4<=appver) {jsver=1.3;}}}} else if (("Netscape"==_S_NAN_)||("Opera"==_S_NAN_)||("Mozilla"==_S_NAN_)){jsver=1.3; appsign='Netscape6';p=_S_NAV_.indexOf(appsign);if (p>=0) {jsver=1.5; } } return jsver;}
function _S_gUniproUN(){var unAllStr=_S_gUCk("UNIPROU");if(""!=unAllStr){var sPos=unAllStr.indexOf(":",2);var unStr=unAllStr.substring(0,sPos);unAllStr=unStr;unStr=unAllStr.substring(0,1)+"_"+unAllStr.substring(2);return unStr;} else{return ""; }}
function _S_gUniproUNid(){var unAllStr=_S_gUCk("nick");var unStr="";if(""!=unAllStr){var sPos=unAllStr.indexOf("(",1);var ePos=unAllStr.indexOf(")",2); if((ePos>0)&&(ePos>sPos)) {unStr=unAllStr.substring(sPos+1,ePos);} } return unStr;}
function _S_gSINAUID(){return _S_gUCk("Apache");}
function _S_sSINAUID(){_S_p2Bcn("gUid_"+Math.random(),cp_rf_d);}
function _S_gsSINAUID(){var uid=_S_gSINAUID();if(""==uid){_S_sSINAUID(); uid=_S_gSINAUID();} return uid;}
function _S_sSINAPUID(_s_PUID){_S_sUCk("SINAGLOBAL",_s_PUID,3650);}
function _S_gSINAPUID(){return _S_gUCk("SINAGLOBAL");}
function _S_gsSINAPUID(){var uid=_S_gSINAPUID();if(""==uid){_S_gfBcn(cp_url);} return uid;}
function _S_gPageInfo(PageID,_sp_rfurl){var now=new Date();var sid=_S_gSINAUID();var pid="pid:"+PageID;var currUrl=_S_PWD_.URL;var currPath=_S_gUrl2Pth(currUrl);var st="st:0";var et="et:"+now.getTime();var hp="hp:"+_S_isHome();var lb="lb:1";var pgls="PGLS:"+_S_gMeta("stencil");var key="keys:"+_S_gMeta("keywords");return sid+"|"+pid+"|"+currPath+"|"+st+"|"+et+"|"+_sp_rfurl+"|"+hp+"|"+lb+"|"+pgls+"|"+key+"|*|";}
function _S_gEnvInfo(){var now=new Date();var pct=0;var ckValue="sz:"+screen.width+"x"+screen.height+"||";ckValue=ckValue+"dp:"+screen.colorDepth+"||";ckValue=ckValue+"ac:"+_S_BN_.appCodeName+"||";ckValue=ckValue+"an:"+_S_NAN_+"||";var ckTmp=_S_NAV_; var pos=0; var tmpValue=""; var len=ckTmp.length; var pos2=0; pos2=ckTmp.indexOf(";",pos); while(pos2>=0) {tmpValue=tmpValue + ckTmp.substring(pos,pos2)+",";pos=pos2+1;pos2=ckTmp.indexOf(";",pos) } tmpValue=tmpValue + ckTmp.substring(pos,len);ckValue=ckValue+"av:"+tmpValue+"||";ckValue=ckValue+"cpu:"+_S_BN_.cpuClass+"||"; ckValue=ckValue+"pf:"+_S_BN_.platform+"||";ckValue=ckValue+"jv:"+_S_gJVer()+"||";ckValue=ckValue+"ct:"+_S_gConType()+"||";ckValue=ckValue+"lg:"+_S_BN_.systemLanguage+"||";ckValue=ckValue+"tz:"+now.getTimezoneOffset()/60;return ckValue;}
function setBaseCookie(shrink, _sp_mpid){if (("undefined"==_sp_mpid)||(""==_sp_mpid)){return; } var sudsid=_S_gsSINAPUID();if(""==sudsid){if(2>_S_FL){_S_PW_.setTimeout("shrinkCookie()",3000);_S_FL=_S_FL+1;}}else{var ckValue=_S_gEnvInfo();var unStr=_S_gUniproUN();var uidStr=_S_gUniproUNid();var envStr="UNIPROINFO="+ckValue+"||un:"+unStr+"||uid:"+uidStr+";";var refUrl=_S_PWD_.referrer;var cPageStr=_S_gPageInfo(_sp_mpid,refUrl);var lbStr=sudsid+"|*|"+cPageStr;lbStr=envStr+"UNIPROPATH="+lbStr+";";_S_p2Bcn(lbStr,cp_rf);}}
function shrinkCookie(p1,p2,p3,p4,p5){try {pUrl=_S_PWD_.URL;pUrl=pUrl.toLowerCase();ps=pUrl.indexOf(_S_DOMAINKEY);if(ps>0){metaList=_S_gMeta("sinachannel");if(""!=metaList) {setBaseCookie(1, metaList);} else{setBaseCookie(1, _S_CID_+_S_DPID_); }}}catch(e){}}

_S_PW_.setTimeout("_S_gsSINAUID()",1000);
_S_PW_.setTimeout("shrinkCookie()",2000);
